version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gostack_desafio06_tests
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
